version: 2
jobs:
  test:
    working_directory: ~/ci
    docker:
      - image: debian:9

    steps:
      - run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip yara make
      - checkout

      - run:
          name: Testing
          command: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
                ignore: master

