rule content_en_language_nsfw {
  strings:
    $s1  =  "2g1c"  fullword wide ascii nocase
    $s2  =  "2 girls 1 cup"  fullword wide ascii nocase
    $s3  =  "acrotomophilia"  fullword wide ascii nocase
    $s4  =  "alabama hot pocket"  fullword wide ascii nocase
    $s5  =  "alaskan pipeline"  fullword wide ascii nocase
    $s6  =  "anal"  fullword wide ascii nocase
    $s7  =  "anilingus"  fullword wide ascii nocase
    $s8  =  "anus"  fullword wide ascii nocase
    $s9  =  "apeshit"  fullword wide ascii nocase
    $s10  =  "arsehole"  fullword wide ascii nocase
    $s12  =  "asshole"  fullword wide ascii nocase
    $s13  =  "assmunch"  fullword wide ascii nocase
    $s14  =  "auto erotic"  fullword wide ascii nocase
    $s15  =  "autoerotic"  fullword wide ascii nocase
    $s16  =  "babeland"  fullword wide ascii nocase
    $s17  =  "baby batter"  fullword wide ascii nocase
    $s18  =  "baby juice"  fullword wide ascii nocase
    $s19  =  "ball gag"  fullword wide ascii nocase
    $s20  =  "ball gravy"  fullword wide ascii nocase
    $s21  =  "ball kicking"  fullword wide ascii nocase
    $s22  =  "ball licking"  fullword wide ascii nocase
    $s23  =  "ball sack"  fullword wide ascii nocase
    $s24  =  "ball sucking"  fullword wide ascii nocase
    $s25  =  "bangbros"  fullword wide ascii nocase
    $s26  =  "bareback"  fullword wide ascii nocase
    $s27  =  "barely legal"  fullword wide ascii nocase
    $s28  =  "barenaked"  fullword wide ascii nocase
    $s30  =  "bastardo"  fullword wide ascii nocase
    $s31  =  "bastinado"  fullword wide ascii nocase
    $s33  =  "bdsm"  fullword wide ascii nocase
    $s34  =  "beaner"  fullword wide ascii nocase
    $s35  =  "beaners"  fullword wide ascii nocase
    $s36  =  "beaver cleaver"  fullword wide ascii nocase
    $s37  =  "beaver lips"  fullword wide ascii nocase
    $s38  =  "bestiality"  fullword wide ascii nocase
    $s39  =  "big black"  fullword wide ascii nocase
    $s40  =  "big breasts"  fullword wide ascii nocase
    $s41  =  "big knockers"  fullword wide ascii nocase
    $s42  =  "big tits"  fullword wide ascii nocase
    $s43  =  "bimbos"  fullword wide ascii nocase
    $s44  =  "birdlock"  fullword wide ascii nocase
    $s45  =  "bitch"  fullword wide ascii nocase
    $s46  =  "bitches"  fullword wide ascii nocase
    $s47  =  "black cock"  fullword wide ascii nocase
    $s48  =  "blonde action"  fullword wide ascii nocase
    $s49  =  "blonde on blonde action"  fullword wide ascii nocase
    $s50  =  "blowjob"  fullword wide ascii nocase
    $s51  =  "blow job"  fullword wide ascii nocase
    $s52  =  "blow your load"  fullword wide ascii nocase
    $s53  =  "blue waffle"  fullword wide ascii nocase
    $s54  =  "blumpkin"  fullword wide ascii nocase
    $s55  =  "bollocks"  fullword wide ascii nocase
    $s56  =  "bondage"  fullword wide ascii nocase
    $s57  =  "boner"  fullword wide ascii nocase
    $s58  =  "boob"  fullword wide ascii nocase
    $s59  =  "boobs"  fullword wide ascii nocase
    $s60  =  "booty call"  fullword wide ascii nocase
    $s61  =  "brown showers"  fullword wide ascii nocase
    $s62  =  "brunette action"  fullword wide ascii nocase
    $s63  =  "bukkake"  fullword wide ascii nocase
    $s64  =  "bulldyke"  fullword wide ascii nocase
    $s65  =  "bullet vibe"  fullword wide ascii nocase
    $s66  =  "bullshit"  fullword wide ascii nocase
    $s67  =  "bung hole"  fullword wide ascii nocase
    $s68  =  "bunghole"  fullword wide ascii nocase
    $s69  =  "busty"  fullword wide ascii nocase
    $s71  =  "buttcheeks"  fullword wide ascii nocase
    $s72  =  "butthole"  fullword wide ascii nocase
    $s73  =  "camel toe"  fullword wide ascii nocase
    $s74  =  "camgirl"  fullword wide ascii nocase
    $s75  =  "camslut"  fullword wide ascii nocase
    $s76  =  "camwhore"  fullword wide ascii nocase
    $s77  =  "carpet muncher"  fullword wide ascii nocase
    $s78  =  "carpetmuncher"  fullword wide ascii nocase
    $s79  =  "chocolate rosebuds"  fullword wide ascii nocase
    $s80  =  "circlejerk"  fullword wide ascii nocase
    $s81  =  "cleveland steamer"  fullword wide ascii nocase
    $s82  =  "clit"  fullword wide ascii nocase
    $s83  =  "clitoris"  fullword wide ascii nocase
    $s84  =  "clover clamps"  fullword wide ascii nocase
    $s85  =  "clusterfuck"  fullword wide ascii nocase
    $s86  =  "cock"  fullword wide ascii nocase
    $s87  =  "cocks"  fullword wide ascii nocase
    $s88  =  "coprolagnia"  fullword wide ascii nocase
    $s89  =  "coprophilia"  fullword wide ascii nocase
    $s90  =  "cornhole"  fullword wide ascii nocase
    $s91  =  "coon"  fullword wide ascii nocase
    $s92  =  "coons"  fullword wide ascii nocase
    $s93  =  "creampie"  fullword wide ascii nocase
    $s95  =  "cumming"  fullword wide ascii nocase
    $s96  =  "cunnilingus"  fullword wide ascii nocase
    $s97  =  "cunt"  fullword wide ascii nocase
    $s98  =  "darkie"  fullword wide ascii nocase
    $s99  =  "date rape"  fullword wide ascii nocase
    $s100  =  "daterape"  fullword wide ascii nocase
    $s101  =  "deep throat"  fullword wide ascii nocase
    $s102  =  "deepthroat"  fullword wide ascii nocase
    $s103  =  "dendrophilia"  fullword wide ascii nocase
    $s105  =  "dildo"  fullword wide ascii nocase
    $s106  =  "dingleberry"  fullword wide ascii nocase
    $s107  =  "dingleberries"  fullword wide ascii nocase
    $s108  =  "dirty pillows"  fullword wide ascii nocase
    $s109  =  "dirty sanchez"  fullword wide ascii nocase
    $s110  =  "doggie style"  fullword wide ascii nocase
    $s111  =  "doggiestyle"  fullword wide ascii nocase
    $s112  =  "doggy style"  fullword wide ascii nocase
    $s113  =  "doggystyle"  fullword wide ascii nocase
    $s114  =  "dog style"  fullword wide ascii nocase
    $s115  =  "dolcett"  fullword wide ascii nocase
    $s116  =  "domination"  fullword wide ascii nocase
    $s117  =  "dominatrix"  fullword wide ascii nocase
    $s118  =  "dommes"  fullword wide ascii nocase
    $s119  =  "donkey punch"  fullword wide ascii nocase
    $s120  =  "double dong"  fullword wide ascii nocase
    $s121  =  "double penetration"  fullword wide ascii nocase
    $s122  =  "dp action"  fullword wide ascii nocase
    $s123  =  "dry hump"  fullword wide ascii nocase
    $s124  =  "dvda"  fullword wide ascii nocase
    $s125  =  "eat my ass"  fullword wide ascii nocase
    $s126  =  "ecchi"  fullword wide ascii nocase
    $s127  =  "ejaculation"  fullword wide ascii nocase
    $s128  =  "erotic"  fullword wide ascii nocase
    $s129  =  "erotism"  fullword wide ascii nocase
    $s130  =  "escort"  fullword wide ascii nocase
    $s131  =  "eunuch"  fullword wide ascii nocase
    $s132  =  "faggot"  fullword wide ascii nocase
    $s133  =  "fecal"  fullword wide ascii nocase
    $s134  =  "felch"  fullword wide ascii nocase
    $s135  =  "fellatio"  fullword wide ascii nocase
    $s136  =  "feltch"  fullword wide ascii nocase
    $s137  =  "female squirting"  fullword wide ascii nocase
    $s138  =  "femdom"  fullword wide ascii nocase
    $s139  =  "figging"  fullword wide ascii nocase
    $s140  =  "fingerbang"  fullword wide ascii nocase
    $s141  =  "fingering"  fullword wide ascii nocase
    $s142  =  "fisting"  fullword wide ascii nocase
    $s143  =  "foot fetish"  fullword wide ascii nocase
    $s144  =  "footjob"  fullword wide ascii nocase
    $s145  =  "frotting"  fullword wide ascii nocase
    $s146  =  "fuck"  fullword wide ascii nocase
    $s147  =  "fuck buttons"  fullword wide ascii nocase
    $s148  =  "fuckin"  fullword wide ascii nocase
    $s149  =  "fucking"  fullword wide ascii nocase
    $s150  =  "fucktards"  fullword wide ascii nocase
    $s151  =  "fudge packer"  fullword wide ascii nocase
    $s152  =  "fudgepacker"  fullword wide ascii nocase
    $s153  =  "futanari"  fullword wide ascii nocase
    $s154  =  "gang bang"  fullword wide ascii nocase
    $s155  =  "gay sex"  fullword wide ascii nocase
    $s156  =  "genitals"  fullword wide ascii nocase
    $s157  =  "giant cock"  fullword wide ascii nocase
    $s158  =  "girl on"  fullword wide ascii nocase
    $s159  =  "girl on top"  fullword wide ascii nocase
    $s160  =  "girls gone wild"  fullword wide ascii nocase
    $s161  =  "goatcx"  fullword wide ascii nocase
    $s162  =  "goatse"  fullword wide ascii nocase
    $s163  =  "god damn"  fullword wide ascii nocase
    $s164  =  "gokkun"  fullword wide ascii nocase
    $s165  =  "golden shower"  fullword wide ascii nocase
    $s166  =  "goodpoop"  fullword wide ascii nocase
    $s167  =  "goo girl"  fullword wide ascii nocase
    $s168  =  "goregasm"  fullword wide ascii nocase
    $s169  =  "grope"  fullword wide ascii nocase
    $s170  =  "group sex"  fullword wide ascii nocase
    $s171  =  "g-spot"  fullword wide ascii nocase
    $s172  =  "guro"  fullword wide ascii nocase
    $s173  =  "hand job"  fullword wide ascii nocase
    $s174  =  "handjob"  fullword wide ascii nocase
    $s175  =  "hard core"  fullword wide ascii nocase
    $s176  =  "hardcore"  fullword wide ascii nocase
    $s177  =  "hentai"  fullword wide ascii nocase
    $s178  =  "homoerotic"  fullword wide ascii nocase
    $s179  =  "honkey"  fullword wide ascii nocase
    $s180  =  "hooker"  fullword wide ascii nocase
    $s181  =  "hot carl"  fullword wide ascii nocase
    $s182  =  "hot chick"  fullword wide ascii nocase
    $s183  =  "how to kill"  fullword wide ascii nocase
    $s184  =  "how to murder"  fullword wide ascii nocase
    $s185  =  "huge fat"  fullword wide ascii nocase
    $s186  =  "humping"  fullword wide ascii nocase
    $s187  =  "incest"  fullword wide ascii nocase
    $s188  =  "intercourse"  fullword wide ascii nocase
    $s189  =  "jack off"  fullword wide ascii nocase
    $s190  =  "jail bait"  fullword wide ascii nocase
    $s191  =  "jailbait"  fullword wide ascii nocase
    $s192  =  "jelly donut"  fullword wide ascii nocase
    $s193  =  "jerk off"  fullword wide ascii nocase
    $s194  =  "jigaboo"  fullword wide ascii nocase
    $s195  =  "jiggaboo"  fullword wide ascii nocase
    $s196  =  "jiggerboo"  fullword wide ascii nocase
    $s197  =  "jizz"  fullword wide ascii nocase
    $s198  =  "juggs"  fullword wide ascii nocase
    $s199  =  "kike"  fullword wide ascii nocase
    $s200  =  "kinbaku"  fullword wide ascii nocase
    $s201  =  "kinkster"  fullword wide ascii nocase
    $s202  =  "kinky"  fullword wide ascii nocase
    $s203  =  "knobbing"  fullword wide ascii nocase
    $s204  =  "leather restraint"  fullword wide ascii nocase
    $s205  =  "leather straight jacket"  fullword wide ascii nocase
    $s206  =  "lemon party"  fullword wide ascii nocase
    $s207  =  "lolita"  fullword wide ascii nocase
    $s209  =  "make me come"  fullword wide ascii nocase
    $s210  =  "male squirting"  fullword wide ascii nocase
    $s211  =  "masturbate"  fullword wide ascii nocase
    $s212  =  "menage a trois"  fullword wide ascii nocase
    $s213  =  "milf"  fullword wide ascii nocase
    $s214  =  "missionary position"  fullword wide ascii nocase
    $s215  =  "motherfucker"  fullword wide ascii nocase
    $s216  =  "mound of venus"  fullword wide ascii nocase
    $s217  =  "mr hands"  fullword wide ascii nocase
    $s218  =  "muff diver"  fullword wide ascii nocase
    $s219  =  "muffdiving"  fullword wide ascii nocase
    $s220  =  "nambla"  fullword wide ascii nocase
    $s221  =  "nawashi"  fullword wide ascii nocase
    $s222  =  "negro"  fullword wide ascii nocase
    $s223  =  "neonazi"  fullword wide ascii nocase
    $s224  =  "nigga"  fullword wide ascii nocase
    $s225  =  "nigger"  fullword wide ascii nocase
    $s226  =  "nig nog"  fullword wide ascii nocase
    $s227  =  "nimphomania"  fullword wide ascii nocase
    $s230  =  "nsfw images"  fullword wide ascii nocase
    $s233  =  "nympho"  fullword wide ascii nocase
    $s234  =  "nymphomania"  fullword wide ascii nocase
    $s235  =  "octopussy"  fullword wide ascii nocase
    $s236  =  "omorashi"  fullword wide ascii nocase
    $s237  =  "one cup two girls"  fullword wide ascii nocase
    $s238  =  "one guy one jar"  fullword wide ascii nocase
    $s239  =  "orgasm"  fullword wide ascii nocase
    $s240  =  "orgy"  fullword wide ascii nocase
    $s241  =  "paedophile"  fullword wide ascii nocase
    $s242  =  "paki"  fullword wide ascii nocase
    $s243  =  "panties"  fullword wide ascii nocase
    $s244  =  "panty"  fullword wide ascii nocase
    $s245  =  "pedobear"  fullword wide ascii nocase
    $s246  =  "pedophile"  fullword wide ascii nocase
    $s247  =  "pegging"  fullword wide ascii nocase
    $s248  =  "penis"  fullword wide ascii nocase
    $s249  =  "phone sex"  fullword wide ascii nocase
    $s250  =  "piece of shit"  fullword wide ascii nocase
    $s251  =  "pissing"  fullword wide ascii nocase
    $s252  =  "piss pig"  fullword wide ascii nocase
    $s253  =  "pisspig"  fullword wide ascii nocase
    $s255  =  "pleasure chest"  fullword wide ascii nocase
    $s256  =  "pole smoker"  fullword wide ascii nocase
    $s257  =  "ponyplay"  fullword wide ascii nocase
    $s259  =  "poon"  fullword wide ascii nocase
    $s260  =  "poontang"  fullword wide ascii nocase
    $s261  =  "punany"  fullword wide ascii nocase
    $s262  =  "poop chute"  fullword wide ascii nocase
    $s263  =  "poopchute"  fullword wide ascii nocase
    $s264  =  "porn"  fullword wide ascii nocase
    $s265  =  "porno"  fullword wide ascii nocase
    $s266  =  "pornography"  fullword wide ascii nocase
    $s267  =  "prince albert piercing"  fullword wide ascii nocase
    $s269  =  "pubes"  fullword wide ascii nocase
    $s270  =  "pussy"  fullword wide ascii nocase
    $s271  =  "queaf"  fullword wide ascii nocase
    $s272  =  "queef"  fullword wide ascii nocase
    $s273  =  "quim"  fullword wide ascii nocase
    $s274  =  "raghead"  fullword wide ascii nocase
    $s275  =  "raging boner"  fullword wide ascii nocase
    $s276  =  "rape"  fullword wide ascii nocase
    $s277  =  "raping"  fullword wide ascii nocase
    $s278  =  "rapist"  fullword wide ascii nocase
    $s280  =  "reverse cowgirl"  fullword wide ascii nocase
    $s281  =  "rimjob"  fullword wide ascii nocase
    $s282  =  "rimming"  fullword wide ascii nocase
    $s283  =  "rosy palm"  fullword wide ascii nocase
    $s284  =  "rosy palm and her 5 sisters"  fullword wide ascii nocase
    $s285  =  "rusty trombone"  fullword wide ascii nocase
    $s286  =  "sadism"  fullword wide ascii nocase
    $s287  =  "santorum"  fullword wide ascii nocase
    $s288  =  "scat"  fullword wide ascii nocase
    $s289  =  "schlong"  fullword wide ascii nocase
    $s290  =  "scissoring"  fullword wide ascii nocase
    $s291  =  "semen"  fullword wide ascii nocase
    $s295  =  "shaved beaver"  fullword wide ascii nocase
    $s296  =  "shaved pussy"  fullword wide ascii nocase
    $s297  =  "shemale"  fullword wide ascii nocase
    $s298  =  "shibari"  fullword wide ascii nocase
    $s299  =  "shit"  fullword wide ascii nocase
    $s300  =  "shitblimp"  fullword wide ascii nocase
    $s301  =  "shitty"  fullword wide ascii nocase
    $s302  =  "shota"  fullword wide ascii nocase
    $s303  =  "shrimping"  fullword wide ascii nocase
    $s304  =  "skeet"  fullword wide ascii nocase
    $s305  =  "slanteye"  fullword wide ascii nocase
    $s306  =  "slut"  fullword wide ascii nocase
    $s308  =  "smut"  fullword wide ascii nocase
    $s309  =  "snatch"  fullword wide ascii nocase
    $s310  =  "snowballing"  fullword wide ascii nocase
    $s311  =  "sodomize"  fullword wide ascii nocase
    $s312  =  "sodomy"  fullword wide ascii nocase
    $s313  =  "spic"  fullword wide ascii nocase
    $s314  =  "splooge"  fullword wide ascii nocase
    $s315  =  "splooge moose"  fullword wide ascii nocase
    $s316  =  "spooge"  fullword wide ascii nocase
    $s317  =  "spread legs"  fullword wide ascii nocase
    $s318  =  "spunk"  fullword wide ascii nocase
    $s319  =  "strap on"  fullword wide ascii nocase
    $s320  =  "strapon"  fullword wide ascii nocase
    $s321  =  "strappado"  fullword wide ascii nocase
    $s322  =  "strip club"  fullword wide ascii nocase
    $s323  =  "style doggy"  fullword wide ascii nocase
    $s326  =  "suicide girls"  fullword wide ascii nocase
    $s327  =  "sultry women"  fullword wide ascii nocase
    $s328  =  "swastika"  fullword wide ascii nocase
    $s329  =  "swinger"  fullword wide ascii nocase
    $s330  =  "tainted love"  fullword wide ascii nocase
    $s331  =  "taste my"  fullword wide ascii nocase
    $s332  =  "tea bagging"  fullword wide ascii nocase
    $s333  =  "threesome"  fullword wide ascii nocase
    $s334  =  "throating"  fullword wide ascii nocase
    $s335  =  "tied up"  fullword wide ascii nocase
    $s336  =  "tight white"  fullword wide ascii nocase
    $s338  =  "tits"  fullword wide ascii nocase
    $s339  =  "titties"  fullword wide ascii nocase
    $s340  =  "titty"  fullword wide ascii nocase
    $s341  =  "tongue in a"  fullword wide ascii nocase
    $s342  =  "topless"  fullword wide ascii nocase
    $s343  =  "tosser"  fullword wide ascii nocase
    $s344  =  "towelhead"  fullword wide ascii nocase
    $s345  =  "tranny"  fullword wide ascii nocase
    $s346  =  "tribadism"  fullword wide ascii nocase
    $s347  =  "tub girl"  fullword wide ascii nocase
    $s348  =  "tubgirl"  fullword wide ascii nocase
    $s349  =  "tushy"  fullword wide ascii nocase
    $s350  =  "twat"  fullword wide ascii nocase
    $s351  =  "twink"  fullword wide ascii nocase
    $s352  =  "twinkie"  fullword wide ascii nocase
    $s353  =  "two girls one cup"  fullword wide ascii nocase
    $s355  =  "upskirt"  fullword wide ascii nocase
    $s356  =  "urethra play"  fullword wide ascii nocase
    $s357  =  "urophilia"  fullword wide ascii nocase
    $s359  =  "venus mound"  fullword wide ascii nocase
    $s360  =  "vibrator"  fullword wide ascii nocase
    $s361  =  "violet wand"  fullword wide ascii nocase
    $s362  =  "vorarephilia"  fullword wide ascii nocase
    $s363  =  "voyeur"  fullword wide ascii nocase
    $s364  =  "vulva"  fullword wide ascii nocase
    $s365  =  "wank"  fullword wide ascii nocase
    $s366  =  "wetback"  fullword wide ascii nocase
    $s367  =  "wet dream"  fullword wide ascii nocase
    $s368  =  "white power"  fullword wide ascii nocase
    $s369  =  "wrapping men"  fullword wide ascii nocase
    $s370  =  "wrinkled starfish"  fullword wide ascii nocase
    $s373  =  "yaoi"  fullword wide ascii nocase
    $s374  =  "yellow showers"  fullword wide ascii nocase
    $s375  =  "yiffy"  fullword wide ascii nocase
    $s376  =  "zoophilia"  fullword wide ascii nocase
    $s377  =  "🖕"  fullword wide nocase

  condition:
    1 of them
}
