rule content_en_language_nsfw {
  strings:
    $  =  "2 girls 1 cup"  fullword wide ascii nocase
    $  =  "2g1c"  fullword wide ascii nocase
    $  =  "acrotomophilia"  fullword wide ascii nocase
    $  =  "alabama hot pocket"  fullword wide ascii nocase
    $  =  "alaskan pipeline"  fullword wide ascii nocase
    $  =  "anal"  fullword wide ascii nocase
    $  =  "anilingus"  fullword wide ascii nocase
    $  =  "anus"  fullword wide ascii nocase
    $  =  "apeshit"  fullword wide ascii nocase
    $  =  "arsehole"  fullword wide ascii nocase
    $  =  "ass"  fullword wide ascii nocase
    $  =  "asshole"  fullword wide ascii nocase
    $  =  "assmunch"  fullword wide ascii nocase
    $  =  "auto erotic"  fullword wide ascii nocase
    $  =  "autoerotic"  fullword wide ascii nocase
    $  =  "babeland"  fullword wide ascii nocase
    $  =  "baby batter"  fullword wide ascii nocase
    $  =  "baby juice"  fullword wide ascii nocase
    $  =  "ball gag"  fullword wide ascii nocase
    $  =  "ball gravy"  fullword wide ascii nocase
    $  =  "ball kicking"  fullword wide ascii nocase
    $  =  "ball licking"  fullword wide ascii nocase
    $  =  "ball sack"  fullword wide ascii nocase
    $  =  "ball sucking"  fullword wide ascii nocase
    $  =  "bangbros"  fullword wide ascii nocase
    $  =  "bareback"  fullword wide ascii nocase
    $  =  "barely legal"  fullword wide ascii nocase
    $  =  "barenaked"  fullword wide ascii nocase
    $  =  "bastard"  fullword wide ascii nocase
    $  =  "bastardo"  fullword wide ascii nocase
    $  =  "bastinado"  fullword wide ascii nocase
    $  =  "bbw"  fullword wide ascii nocase
    $  =  "bdsm"  fullword wide ascii nocase
    $  =  "beaner"  fullword wide ascii nocase
    $  =  "beaners"  fullword wide ascii nocase
    $  =  "beaver cleaver"  fullword wide ascii nocase
    $  =  "beaver lips"  fullword wide ascii nocase
    $  =  "bestiality"  fullword wide ascii nocase
    $  =  "big black"  fullword wide ascii nocase
    $  =  "big breasts"  fullword wide ascii nocase
    $  =  "big knockers"  fullword wide ascii nocase
    $  =  "big tits"  fullword wide ascii nocase
    $  =  "bimbos"  fullword wide ascii nocase
    $  =  "birdlock"  fullword wide ascii nocase
    $  =  "bitch"  fullword wide ascii nocase
    $  =  "bitches"  fullword wide ascii nocase
    $  =  "black cock"  fullword wide ascii nocase
    $  =  "blonde action"  fullword wide ascii nocase
    $  =  "blonde on blonde action"  fullword wide ascii nocase
    $  =  "blow job"  fullword wide ascii nocase
    $  =  "blow your load"  fullword wide ascii nocase
    $  =  "blowjob"  fullword wide ascii nocase
    $  =  "blue waffle"  fullword wide ascii nocase
    $  =  "blumpkin"  fullword wide ascii nocase
    $  =  "bollocks"  fullword wide ascii nocase
    $  =  "bondage"  fullword wide ascii nocase
    $  =  "boner"  fullword wide ascii nocase
    $  =  "boob"  fullword wide ascii nocase
    $  =  "boobs"  fullword wide ascii nocase
    $  =  "booty call"  fullword wide ascii nocase
    $  =  "brown showers"  fullword wide ascii nocase
    $  =  "brunette action"  fullword wide ascii nocase
    $  =  "bukkake"  fullword wide ascii nocase
    $  =  "bulldyke"  fullword wide ascii nocase
    $  =  "bullet vibe"  fullword wide ascii nocase
    $  =  "bullshit"  fullword wide ascii nocase
    $  =  "bung hole"  fullword wide ascii nocase
    $  =  "bunghole"  fullword wide ascii nocase
    $  =  "busty"  fullword wide ascii nocase
    $  =  "butt"  fullword wide ascii nocase
    $  =  "buttcheeks"  fullword wide ascii nocase
    $  =  "butthole"  fullword wide ascii nocase
    $  =  "camel toe"  fullword wide ascii nocase
    $  =  "camgirl"  fullword wide ascii nocase
    $  =  "camslut"  fullword wide ascii nocase
    $  =  "camwhore"  fullword wide ascii nocase
    $  =  "carpet muncher"  fullword wide ascii nocase
    $  =  "carpetmuncher"  fullword wide ascii nocase
    $  =  "chocolate rosebuds"  fullword wide ascii nocase
    $  =  "circlejerk"  fullword wide ascii nocase
    $  =  "cleveland steamer"  fullword wide ascii nocase
    $  =  "clit"  fullword wide ascii nocase
    $  =  "clitoris"  fullword wide ascii nocase
    $  =  "clover clamps"  fullword wide ascii nocase
    $  =  "clusterfuck"  fullword wide ascii nocase
    $  =  "cock"  fullword wide ascii nocase
    $  =  "cocks"  fullword wide ascii nocase
    $  =  "coon"  fullword wide ascii nocase
    $  =  "coons"  fullword wide ascii nocase
    $  =  "coprolagnia"  fullword wide ascii nocase
    $  =  "coprophilia"  fullword wide ascii nocase
    $  =  "cornhole"  fullword wide ascii nocase
    $  =  "creampie"  fullword wide ascii nocase
    $  =  "cum"  fullword wide ascii nocase
    $  =  "cumming"  fullword wide ascii nocase
    $  =  "cunnilingus"  fullword wide ascii nocase
    $  =  "cunt"  fullword wide ascii nocase
    $  =  "darkie"  fullword wide ascii nocase
    $  =  "date rape"  fullword wide ascii nocase
    $  =  "daterape"  fullword wide ascii nocase
    $  =  "deep throat"  fullword wide ascii nocase
    $  =  "deepthroat"  fullword wide ascii nocase
    $  =  "dendrophilia"  fullword wide ascii nocase
    $  =  "dick"  fullword wide ascii nocase
    $  =  "dildo"  fullword wide ascii nocase
    $  =  "dingleberries"  fullword wide ascii nocase
    $  =  "dingleberry"  fullword wide ascii nocase
    $  =  "dirty pillows"  fullword wide ascii nocase
    $  =  "dirty sanchez"  fullword wide ascii nocase
    $  =  "dog style"  fullword wide ascii nocase
    $  =  "doggie style"  fullword wide ascii nocase
    $  =  "doggiestyle"  fullword wide ascii nocase
    $  =  "doggy style"  fullword wide ascii nocase
    $  =  "doggystyle"  fullword wide ascii nocase
    $  =  "dolcett"  fullword wide ascii nocase
    $  =  "domination"  fullword wide ascii nocase
    $  =  "dominatrix"  fullword wide ascii nocase
    $  =  "dommes"  fullword wide ascii nocase
    $  =  "donkey punch"  fullword wide ascii nocase
    $  =  "double dong"  fullword wide ascii nocase
    $  =  "double penetration"  fullword wide ascii nocase
    $  =  "dp action"  fullword wide ascii nocase
    $  =  "dry hump"  fullword wide ascii nocase
    $  =  "dvda"  fullword wide ascii nocase
    $  =  "eat my ass"  fullword wide ascii nocase
    $  =  "ecchi"  fullword wide ascii nocase
    $  =  "ejaculation"  fullword wide ascii nocase
    $  =  "erotic"  fullword wide ascii nocase
    $  =  "erotism"  fullword wide ascii nocase
    $  =  "escort"  fullword wide ascii nocase
    $  =  "eunuch"  fullword wide ascii nocase
    $  =  "faggot"  fullword wide ascii nocase
    $  =  "fecal"  fullword wide ascii nocase
    $  =  "felch"  fullword wide ascii nocase
    $  =  "fellatio"  fullword wide ascii nocase
    $  =  "feltch"  fullword wide ascii nocase
    $  =  "female squirting"  fullword wide ascii nocase
    $  =  "femdom"  fullword wide ascii nocase
    $  =  "figging"  fullword wide ascii nocase
    $  =  "fingerbang"  fullword wide ascii nocase
    $  =  "fingering"  fullword wide ascii nocase
    $  =  "fisting"  fullword wide ascii nocase
    $  =  "foot fetish"  fullword wide ascii nocase
    $  =  "footjob"  fullword wide ascii nocase
    $  =  "frotting"  fullword wide ascii nocase
    $  =  "fuck"  fullword wide ascii nocase
    $  =  "fuck buttons"  fullword wide ascii nocase
    $  =  "fuckin"  fullword wide ascii nocase
    $  =  "fucking"  fullword wide ascii nocase
    $  =  "fucktards"  fullword wide ascii nocase
    $  =  "fudge packer"  fullword wide ascii nocase
    $  =  "fudgepacker"  fullword wide ascii nocase
    $  =  "futanari"  fullword wide ascii nocase
    $  =  "g-spot"  fullword wide ascii nocase
    $  =  "gang bang"  fullword wide ascii nocase
    $  =  "gay sex"  fullword wide ascii nocase
    $  =  "genitals"  fullword wide ascii nocase
    $  =  "giant cock"  fullword wide ascii nocase
    $  =  "girl on"  fullword wide ascii nocase
    $  =  "girl on top"  fullword wide ascii nocase
    $  =  "girls gone wild"  fullword wide ascii nocase
    $  =  "goatcx"  fullword wide ascii nocase
    $  =  "goatse"  fullword wide ascii nocase
    $  =  "god damn"  fullword wide ascii nocase
    $  =  "gokkun"  fullword wide ascii nocase
    $  =  "golden shower"  fullword wide ascii nocase
    $  =  "goo girl"  fullword wide ascii nocase
    $  =  "goodpoop"  fullword wide ascii nocase
    $  =  "goregasm"  fullword wide ascii nocase
    $  =  "grope"  fullword wide ascii nocase
    $  =  "group sex"  fullword wide ascii nocase
    $  =  "guro"  fullword wide ascii nocase
    $  =  "hand job"  fullword wide ascii nocase
    $  =  "handjob"  fullword wide ascii nocase
    $  =  "hard core"  fullword wide ascii nocase
    $  =  "hardcore"  fullword wide ascii nocase
    $  =  "hentai"  fullword wide ascii nocase
    $  =  "homoerotic"  fullword wide ascii nocase
    $  =  "honkey"  fullword wide ascii nocase
    $  =  "hooker"  fullword wide ascii nocase
    $  =  "hot carl"  fullword wide ascii nocase
    $  =  "hot chick"  fullword wide ascii nocase
    $  =  "how to kill"  fullword wide ascii nocase
    $  =  "how to murder"  fullword wide ascii nocase
    $  =  "huge fat"  fullword wide ascii nocase
    $  =  "humping"  fullword wide ascii nocase
    $  =  "incest"  fullword wide ascii nocase
    $  =  "jack off"  fullword wide ascii nocase
    $  =  "jail bait"  fullword wide ascii nocase
    $  =  "jailbait"  fullword wide ascii nocase
    $  =  "jelly donut"  fullword wide ascii nocase
    $  =  "jerk off"  fullword wide ascii nocase
    $  =  "jigaboo"  fullword wide ascii nocase
    $  =  "jiggaboo"  fullword wide ascii nocase
    $  =  "jiggerboo"  fullword wide ascii nocase
    $  =  "jizz"  fullword wide ascii nocase
    $  =  "juggs"  fullword wide ascii nocase
    $  =  "kike"  fullword wide ascii nocase
    $  =  "kinbaku"  fullword wide ascii nocase
    $  =  "kinkster"  fullword wide ascii nocase
    $  =  "kinky"  fullword wide ascii nocase
    $  =  "knobbing"  fullword wide ascii nocase
    $  =  "leather restraint"  fullword wide ascii nocase
    $  =  "leather straight jacket"  fullword wide ascii nocase
    $  =  "lemon party"  fullword wide ascii nocase
    $  =  "lolita"  fullword wide ascii nocase
    $  =  "lovemaking"  fullword wide ascii nocase
    $  =  "make me come"  fullword wide ascii nocase
    $  =  "male squirting"  fullword wide ascii nocase
    $  =  "masturbate"  fullword wide ascii nocase
    $  =  "menage a trois"  fullword wide ascii nocase
    $  =  "milf"  fullword wide ascii nocase
    $  =  "missionary position"  fullword wide ascii nocase
    $  =  "motherfucker"  fullword wide ascii nocase
    $  =  "mound of venus"  fullword wide ascii nocase
    $  =  "mr hands"  fullword wide ascii nocase
    $  =  "muff diver"  fullword wide ascii nocase
    $  =  "muffdiving"  fullword wide ascii nocase
    $  =  "nambla"  fullword wide ascii nocase
    $  =  "nawashi"  fullword wide ascii nocase
    $  =  "negro"  fullword wide ascii nocase
    $  =  "neonazi"  fullword wide ascii nocase
    $  =  "nig nog"  fullword wide ascii nocase
    $  =  "nigga"  fullword wide ascii nocase
    $  =  "nigger"  fullword wide ascii nocase
    $  =  "nimphomania"  fullword wide ascii nocase
    $  =  "nipple"  fullword wide ascii nocase
    $  =  "nipples"  fullword wide ascii nocase
    $  =  "nsfw images"  fullword wide ascii nocase
    $  =  "nympho"  fullword wide ascii nocase
    $  =  "nymphomania"  fullword wide ascii nocase
    $  =  "octopussy"  fullword wide ascii nocase
    $  =  "omorashi"  fullword wide ascii nocase
    $  =  "one cup two girls"  fullword wide ascii nocase
    $  =  "one guy one jar"  fullword wide ascii nocase
    $  =  "orgasm"  fullword wide ascii nocase
    $  =  "orgy"  fullword wide ascii nocase
    $  =  "paedophile"  fullword wide ascii nocase
    $  =  "paki"  fullword wide ascii nocase
    $  =  "panties"  fullword wide ascii nocase
    $  =  "panty"  fullword wide ascii nocase
    $  =  "pedobear"  fullword wide ascii nocase
    $  =  "pedophile"  fullword wide ascii nocase
    $  =  "pegging"  fullword wide ascii nocase
    $  =  "penis"  fullword wide ascii nocase
    $  =  "phone sex"  fullword wide ascii nocase
    $  =  "piece of shit"  fullword wide ascii nocase
    $  =  "piss pig"  fullword wide ascii nocase
    $  =  "pissing"  fullword wide ascii nocase
    $  =  "pisspig"  fullword wide ascii nocase
    $  =  "playboy"  fullword wide ascii nocase
    $  =  "pleasure chest"  fullword wide ascii nocase
    $  =  "pole smoker"  fullword wide ascii nocase
    $  =  "ponyplay"  fullword wide ascii nocase
    $  =  "poof"  fullword wide ascii nocase
    $  =  "poon"  fullword wide ascii nocase
    $  =  "poontang"  fullword wide ascii nocase
    $  =  "poop chute"  fullword wide ascii nocase
    $  =  "poopchute"  fullword wide ascii nocase
    $  =  "porn"  fullword wide ascii nocase
    $  =  "porno"  fullword wide ascii nocase
    $  =  "pornography"  fullword wide ascii nocase
    $  =  "prince albert piercing"  fullword wide ascii nocase
    $  =  "pthc"  fullword wide ascii nocase
    $  =  "pubes"  fullword wide ascii nocase
    $  =  "punany"  fullword wide ascii nocase
    $  =  "pussy"  fullword wide ascii nocase
    $  =  "queaf"  fullword wide ascii nocase
    $  =  "queef"  fullword wide ascii nocase
    $  =  "quim"  fullword wide ascii nocase
    $  =  "raghead"  fullword wide ascii nocase
    $  =  "raging boner"  fullword wide ascii nocase
    $  =  "rape"  fullword wide ascii nocase
    $  =  "raping"  fullword wide ascii nocase
    $  =  "rapist"  fullword wide ascii nocase
    $  =  "rectum"  fullword wide ascii nocase
    $  =  "reverse cowgirl"  fullword wide ascii nocase
    $  =  "rimjob"  fullword wide ascii nocase
    $  =  "rimming"  fullword wide ascii nocase
    $  =  "rosy palm"  fullword wide ascii nocase
    $  =  "rosy palm and her 5 sisters"  fullword wide ascii nocase
    $  =  "rusty trombone"  fullword wide ascii nocase
    $  =  "s&m"  fullword wide ascii nocase
    $  =  "sadism"  fullword wide ascii nocase
    $  =  "santorum"  fullword wide ascii nocase
    $  =  "scat"  fullword wide ascii nocase
    $  =  "schlong"  fullword wide ascii nocase
    $  =  "scissoring"  fullword wide ascii nocase
    $  =  "semen"  fullword wide ascii nocase
    $  =  "sex"  fullword wide ascii nocase
    $  =  "sexo"  fullword wide ascii nocase
    $  =  "sexy"  fullword wide ascii nocase
    $  =  "shaved beaver"  fullword wide ascii nocase
    $  =  "shaved pussy"  fullword wide ascii nocase
    $  =  "shemale"  fullword wide ascii nocase
    $  =  "shibari"  fullword wide ascii nocase
    $  =  "shit"  fullword wide ascii nocase
    $  =  "shitblimp"  fullword wide ascii nocase
    $  =  "shitty"  fullword wide ascii nocase
    $  =  "shota"  fullword wide ascii nocase
    $  =  "shrimping"  fullword wide ascii nocase
    $  =  "skeet"  fullword wide ascii nocase
    $  =  "slanteye"  fullword wide ascii nocase
    $  =  "slut"  fullword wide ascii nocase
    $  =  "smut"  fullword wide ascii nocase
    $  =  "snatch"  fullword wide ascii nocase
    $  =  "snowballing"  fullword wide ascii nocase
    $  =  "sodomize"  fullword wide ascii nocase
    $  =  "sodomy"  fullword wide ascii nocase
    $  =  "spic"  fullword wide ascii nocase
    $  =  "splooge"  fullword wide ascii nocase
    $  =  "splooge moose"  fullword wide ascii nocase
    $  =  "spooge"  fullword wide ascii nocase
    $  =  "spread legs"  fullword wide ascii nocase
    $  =  "spunk"  fullword wide ascii nocase
    $  =  "strap on"  fullword wide ascii nocase
    $  =  "strapon"  fullword wide ascii nocase
    $  =  "strappado"  fullword wide ascii nocase
    $  =  "strip club"  fullword wide ascii nocase
    $  =  "style doggy"  fullword wide ascii nocase
    $  =  "suck"  fullword wide ascii nocase
    $  =  "sucks"  fullword wide ascii nocase
    $  =  "suicide girls"  fullword wide ascii nocase
    $  =  "sultry women"  fullword wide ascii nocase
    $  =  "swastika"  fullword wide ascii nocase
    $  =  "swinger"  fullword wide ascii nocase
    $  =  "tainted love"  fullword wide ascii nocase
    $  =  "taste my"  fullword wide ascii nocase
    $  =  "tea bagging"  fullword wide ascii nocase
    $  =  "threesome"  fullword wide ascii nocase
    $  =  "throating"  fullword wide ascii nocase
    $  =  "tied up"  fullword wide ascii nocase
    $  =  "tight white"  fullword wide ascii nocase
    $  =  "tit"  fullword wide ascii nocase
    $  =  "tits"  fullword wide ascii nocase
    $  =  "titties"  fullword wide ascii nocase
    $  =  "titty"  fullword wide ascii nocase
    $  =  "tongue in a"  fullword wide ascii nocase
    $  =  "topless"  fullword wide ascii nocase
    $  =  "tosser"  fullword wide ascii nocase
    $  =  "towelhead"  fullword wide ascii nocase
    $  =  "tranny"  fullword wide ascii nocase
    $  =  "tribadism"  fullword wide ascii nocase
    $  =  "tub girl"  fullword wide ascii nocase
    $  =  "tubgirl"  fullword wide ascii nocase
    $  =  "tushy"  fullword wide ascii nocase
    $  =  "twat"  fullword wide ascii nocase
    $  =  "twink"  fullword wide ascii nocase
    $  =  "twinkie"  fullword wide ascii nocase
    $  =  "two girls one cup"  fullword wide ascii nocase
    $  =  "upskirt"  fullword wide ascii nocase
    $  =  "urethra play"  fullword wide ascii nocase
    $  =  "urophilia"  fullword wide ascii nocase
    $  =  "vagina"  fullword wide ascii nocase
    $  =  "venus mound"  fullword wide ascii nocase
    $  =  "vibrator"  fullword wide ascii nocase
    $  =  "violet wand"  fullword wide ascii nocase
    $  =  "vorarephilia"  fullword wide ascii nocase
    $  =  "voyeur"  fullword wide ascii nocase
    $  =  "vulva"  fullword wide ascii nocase
    $  =  "wank"  fullword wide ascii nocase
    $  =  "wet dream"  fullword wide ascii nocase
    $  =  "wetback"  fullword wide ascii nocase
    $  =  "white power"  fullword wide ascii nocase
    $  =  "wrapping men"  fullword wide ascii nocase
    $  =  "wrinkled starfish"  fullword wide ascii nocase
    $  =  "yaoi"  fullword wide ascii nocase
    $  =  "yellow showers"  fullword wide ascii nocase
    $  =  "yiffy"  fullword wide ascii nocase
    $  =  "zoophilia"  fullword wide ascii nocase
    $  =  "🖕"  fullword wide ascii nocase
  condition:
    1 of them
}
