rule content_es_language_nsfw {
  strings:
    $  =  "Asesinato"  fullword wide ascii nocase
    $  =  "Bollera"  fullword wide ascii nocase
    $  =  "Cabron"  fullword wide ascii nocase
    $  =  "Cabrón"  fullword wide ascii nocase
    $  =  "Caca"  fullword wide ascii nocase
    $  =  "Chupada"  fullword wide ascii nocase
    $  =  "Chupapollas"  fullword wide ascii nocase
    $  =  "Chupetón"  fullword wide ascii nocase
    $  =  "Concha de tu madre"  fullword wide ascii nocase
    $  =  "Coprofagía"  fullword wide ascii nocase
    $  =  "Coño"  fullword wide ascii nocase
    $  =  "Culo"  fullword wide ascii nocase
    $  =  "Drogas"  fullword wide ascii nocase
    $  =  "Esperma"  fullword wide ascii nocase
    $  =  "Fiesta de salchichas"  fullword wide ascii nocase
    $  =  "Follador"  fullword wide ascii nocase
    $  =  "Follar"  fullword wide ascii nocase
    $  =  "Gilipichis"  fullword wide ascii nocase
    $  =  "Gilipollas"  fullword wide ascii nocase
    $  =  "Hacer una paja"  fullword wide ascii nocase
    $  =  "Haciendo el amor"  fullword wide ascii nocase
    $  =  "Heroína"  fullword wide ascii nocase
    $  =  "Hija de puta"  fullword wide ascii nocase
    $  =  "Hijaputa"  fullword wide ascii nocase
    $  =  "Hijo de puta"  fullword wide ascii nocase
    $  =  "Hijoputa"  fullword wide ascii nocase
    $  =  "Idiota"  fullword wide ascii nocase
    $  =  "Imbécil"  fullword wide ascii nocase
    $  =  "Jilipollas"  fullword wide ascii nocase
    $  =  "Kapullo"  fullword wide ascii nocase
    $  =  "Lameculos"  fullword wide ascii nocase
    $  =  "Maciza"  fullword wide ascii nocase
    $  =  "Macizorra"  fullword wide ascii nocase
    $  =  "Mamada"  fullword wide ascii nocase
    $  =  "Marica"  fullword wide ascii nocase
    $  =  "Mariconazo"  fullword wide ascii nocase
    $  =  "Maricón"  fullword wide ascii nocase
    $  =  "Mierda"  fullword wide ascii nocase
    $  =  "Nazi"  fullword wide ascii nocase
    $  =  "Orina"  fullword wide ascii nocase
    $  =  "Pedo"  fullword wide ascii nocase
    $  =  "Pervertido"  fullword wide ascii nocase
    $  =  "Pezón"  fullword wide ascii nocase
    $  =  "Pinche"  fullword wide ascii nocase
    $  =  "Pis"  fullword wide ascii nocase
    $  =  "Prostituta"  fullword wide ascii nocase
    $  =  "Puta"  fullword wide ascii nocase
    $  =  "Racista"  fullword wide ascii nocase
    $  =  "Ramera"  fullword wide ascii nocase
    $  =  "Semen"  fullword wide ascii nocase
    $  =  "Sexo"  fullword wide ascii nocase
    $  =  "Sexo oral"  fullword wide ascii nocase
    $  =  "Soplagaitas"  fullword wide ascii nocase
    $  =  "Soplapollas"  fullword wide ascii nocase
    $  =  "Sádico"  fullword wide ascii nocase
    $  =  "Tetas grandes"  fullword wide ascii nocase
    $  =  "Travesti"  fullword wide ascii nocase
    $  =  "Trio"  fullword wide ascii nocase
    $  =  "Tía buena"  fullword wide ascii nocase
    $  =  "Verga"  fullword wide ascii nocase
    $  =  "Vulva"  fullword wide ascii nocase
    $  =  "asno"  fullword wide ascii nocase
    $  =  "bastardo"  fullword wide ascii nocase
    $  =  "concha"  fullword wide ascii nocase
    $  =  "infierno"  fullword wide ascii nocase
    $  =  "maldito"  fullword wide ascii nocase
    $  =  "martillo"  fullword wide ascii nocase
    $  =  "vete a la mierda"  fullword wide ascii nocase
  condition:
    1 of them
}
