rule content_fi_language_nsfw {
  strings:
    $  =  "alfred nussi"  fullword wide ascii nocase
    $  =  "bylsiä"  fullword wide ascii nocase
    $  =  "haahka"  fullword wide ascii nocase
    $  =  "haista paska"  fullword wide ascii nocase
    $  =  "haista vittu"  fullword wide ascii nocase
    $  =  "hatullinen"  fullword wide ascii nocase
    $  =  "helvetisti"  fullword wide ascii nocase
    $  =  "hevonkuusi"  fullword wide ascii nocase
    $  =  "hevonpaska"  fullword wide ascii nocase
    $  =  "hevonperse"  fullword wide ascii nocase
    $  =  "hevonvittu"  fullword wide ascii nocase
    $  =  "hevonvitunperse"  fullword wide ascii nocase
    $  =  "hitosti"  fullword wide ascii nocase
    $  =  "hitto"  fullword wide ascii nocase
    $  =  "huorata"  fullword wide ascii nocase
    $  =  "hässiä"  fullword wide ascii nocase
    $  =  "juosten kustu"  fullword wide ascii nocase
    $  =  "jutku"  fullword wide ascii nocase
    $  =  "jutsku"  fullword wide ascii nocase
    $  =  "jätkä"  fullword wide ascii nocase
    $  =  "kananpaska"  fullword wide ascii nocase
    $  =  "koiranpaska"  fullword wide ascii nocase
    $  =  "kuin esterin perseestä"  fullword wide ascii nocase
    $  =  "kulli"  fullword wide ascii nocase
    $  =  "kullinluikaus"  fullword wide ascii nocase
    $  =  "kuppainen"  fullword wide ascii nocase
    $  =  "kusaista"  fullword wide ascii nocase
    $  =  "kuseksia"  fullword wide ascii nocase
    $  =  "kusettaa"  fullword wide ascii nocase
    $  =  "kusi"  fullword wide ascii nocase
    $  =  "kusipää"  fullword wide ascii nocase
    $  =  "kusta"  fullword wide ascii nocase
    $  =  "kyrpiintynyt"  fullword wide ascii nocase
    $  =  "kyrpiintyä"  fullword wide ascii nocase
    $  =  "kyrpiä"  fullword wide ascii nocase
    $  =  "kyrpä"  fullword wide ascii nocase
    $  =  "kyrpänaama"  fullword wide ascii nocase
    $  =  "kyrvitys"  fullword wide ascii nocase
    $  =  "lahtari"  fullword wide ascii nocase
    $  =  "lutka"  fullword wide ascii nocase
    $  =  "molo"  fullword wide ascii nocase
    $  =  "molopää"  fullword wide ascii nocase
    $  =  "mulkero"  fullword wide ascii nocase
    $  =  "mulkku"  fullword wide ascii nocase
    $  =  "mulkvisti"  fullword wide ascii nocase
    $  =  "muna"  fullword wide ascii nocase
    $  =  "munapää"  fullword wide ascii nocase
    $  =  "munaton"  fullword wide ascii nocase
    $  =  "mutakuono"  fullword wide ascii nocase
    $  =  "mutiainen"  fullword wide ascii nocase
    $  =  "naida"  fullword wide ascii nocase
    $  =  "nainti"  fullword wide ascii nocase
    $  =  "narttu"  fullword wide ascii nocase
    $  =  "neekeri"  fullword wide ascii nocase
    $  =  "nekru"  fullword wide ascii nocase
    $  =  "nuolla persettä"  fullword wide ascii nocase
    $  =  "nussia"  fullword wide ascii nocase
    $  =  "nussija"  fullword wide ascii nocase
    $  =  "nussinta"  fullword wide ascii nocase
    $  =  "paljaalla"  fullword wide ascii nocase
    $  =  "palli"  fullword wide ascii nocase
    $  =  "pallit"  fullword wide ascii nocase
    $  =  "paneskella"  fullword wide ascii nocase
    $  =  "panettaa"  fullword wide ascii nocase
    $  =  "panna"  fullword wide ascii nocase
    $  =  "pano"  fullword wide ascii nocase
    $  =  "pantava"  fullword wide ascii nocase
    $  =  "paska"  fullword wide ascii nocase
    $  =  "paskainen"  fullword wide ascii nocase
    $  =  "paskamainen"  fullword wide ascii nocase
    $  =  "paskanmarjat"  fullword wide ascii nocase
    $  =  "paskantaa"  fullword wide ascii nocase
    $  =  "paskapuhe"  fullword wide ascii nocase
    $  =  "paskapää"  fullword wide ascii nocase
    $  =  "paskattaa"  fullword wide ascii nocase
    $  =  "paskiainen"  fullword wide ascii nocase
    $  =  "paskoa"  fullword wide ascii nocase
    $  =  "pehko"  fullword wide ascii nocase
    $  =  "pentele"  fullword wide ascii nocase
    $  =  "perkele"  fullword wide ascii nocase
    $  =  "perkeleesti"  fullword wide ascii nocase
    $  =  "persaukinen"  fullword wide ascii nocase
    $  =  "perse"  fullword wide ascii nocase
    $  =  "perseennuolija"  fullword wide ascii nocase
    $  =  "perseet olalla"  fullword wide ascii nocase
    $  =  "persereikä"  fullword wide ascii nocase
    $  =  "perseääliö"  fullword wide ascii nocase
    $  =  "persläpi"  fullword wide ascii nocase
    $  =  "perspano"  fullword wide ascii nocase
    $  =  "persvako"  fullword wide ascii nocase
    $  =  "pilkunnussija"  fullword wide ascii nocase
    $  =  "pillu"  fullword wide ascii nocase
    $  =  "pillut"  fullword wide ascii nocase
    $  =  "pipari"  fullword wide ascii nocase
    $  =  "piru"  fullword wide ascii nocase
    $  =  "pistää"  fullword wide ascii nocase
    $  =  "pyllyvako"  fullword wide ascii nocase
    $  =  "reikä"  fullword wide ascii nocase
    $  =  "reva"  fullword wide ascii nocase
    $  =  "ripsipiirakka"  fullword wide ascii nocase
    $  =  "runkata"  fullword wide ascii nocase
    $  =  "runkkari"  fullword wide ascii nocase
    $  =  "runkkaus"  fullword wide ascii nocase
    $  =  "runkku"  fullword wide ascii nocase
    $  =  "ryssä"  fullword wide ascii nocase
    $  =  "rättipää"  fullword wide ascii nocase
    $  =  "saatanasti"  fullword wide ascii nocase
    $  =  "suklaaosasto"  fullword wide ascii nocase
    $  =  "tavara"  fullword wide ascii nocase
    $  =  "toosa"  fullword wide ascii nocase
    $  =  "tuhkaluukku"  fullword wide ascii nocase
    $  =  "tumputtaa"  fullword wide ascii nocase
    $  =  "turpasauna"  fullword wide ascii nocase
    $  =  "tussu"  fullword wide ascii nocase
    $  =  "tussukka"  fullword wide ascii nocase
    $  =  "tussut"  fullword wide ascii nocase
    $  =  "vakipano"  fullword wide ascii nocase
    $  =  "vetää käteen"  fullword wide ascii nocase
    $  =  "viiksi"  fullword wide ascii nocase
    $  =  "vittu"  fullword wide ascii nocase
    $  =  "vittuilla"  fullword wide ascii nocase
    $  =  "vittuilu"  fullword wide ascii nocase
    $  =  "vittumainen"  fullword wide ascii nocase
    $  =  "vittuuntua"  fullword wide ascii nocase
    $  =  "vittuuntunut"  fullword wide ascii nocase
    $  =  "vitun"  fullword wide ascii nocase
    $  =  "vitusti"  fullword wide ascii nocase
    $  =  "vituttaa"  fullword wide ascii nocase
    $  =  "vitutus"  fullword wide ascii nocase
    $  =  "äpärä"  fullword wide ascii nocase
  condition:
    1 of them
}
