rule content_fr_language_nsfw {
  strings:
    $  =  "MALPT"  fullword wide ascii nocase
    $  =  "baiser"  fullword wide ascii nocase
    $  =  "bander"  fullword wide ascii nocase
    $  =  "bigornette"  fullword wide ascii nocase
    $  =  "bite"  fullword wide ascii nocase
    $  =  "bitte"  fullword wide ascii nocase
    $  =  "bloblos"  fullword wide ascii nocase
    $  =  "bordel"  fullword wide ascii nocase
    $  =  "bosser"  fullword wide ascii nocase
    $  =  "bourré"  fullword wide ascii nocase
    $  =  "bourrée"  fullword wide ascii nocase
    $  =  "brackmard"  fullword wide ascii nocase
    $  =  "branlage"  fullword wide ascii nocase
    $  =  "branler"  fullword wide ascii nocase
    $  =  "branlette"  fullword wide ascii nocase
    $  =  "branleur"  fullword wide ascii nocase
    $  =  "branleuse"  fullword wide ascii nocase
    $  =  "brouter le cresson"  fullword wide ascii nocase
    $  =  "caca"  fullword wide ascii nocase
    $  =  "cailler"  fullword wide ascii nocase
    $  =  "chatte"  fullword wide ascii nocase
    $  =  "chiasse"  fullword wide ascii nocase
    $  =  "chier"  fullword wide ascii nocase
    $  =  "chiottes"  fullword wide ascii nocase
    $  =  "clito"  fullword wide ascii nocase
    $  =  "clitoris"  fullword wide ascii nocase
    $  =  "con"  fullword wide ascii nocase
    $  =  "connard"  fullword wide ascii nocase
    $  =  "connasse"  fullword wide ascii nocase
    $  =  "conne"  fullword wide ascii nocase
    $  =  "couilles"  fullword wide ascii nocase
    $  =  "cramouille"  fullword wide ascii nocase
    $  =  "cul"  fullword wide ascii nocase
    $  =  "drague"  fullword wide ascii nocase
    $  =  "déconne"  fullword wide ascii nocase
    $  =  "déconner"  fullword wide ascii nocase
    $  =  "emmerdant"  fullword wide ascii nocase
    $  =  "emmerder"  fullword wide ascii nocase
    $  =  "emmerdeur"  fullword wide ascii nocase
    $  =  "emmerdeuse"  fullword wide ascii nocase
    $  =  "enculeur"  fullword wide ascii nocase
    $  =  "enculeurs"  fullword wide ascii nocase
    $  =  "enculé"  fullword wide ascii nocase
    $  =  "enculée"  fullword wide ascii nocase
    $  =  "enfoiré"  fullword wide ascii nocase
    $  =  "enfoirée"  fullword wide ascii nocase
    $  =  "fille de pute"  fullword wide ascii nocase
    $  =  "fils de pute"  fullword wide ascii nocase
    $  =  "folle"  fullword wide ascii nocase
    $  =  "foutre"  fullword wide ascii nocase
    $  =  "gerbe"  fullword wide ascii nocase
    $  =  "gerber"  fullword wide ascii nocase
    $  =  "gouine"  fullword wide ascii nocase
    $  =  "grande folle"  fullword wide ascii nocase
    $  =  "grogniasse"  fullword wide ascii nocase
    $  =  "gueule"  fullword wide ascii nocase
    $  =  "jouir"  fullword wide ascii nocase
    $  =  "la putain de ta mère"  fullword wide ascii nocase
    $  =  "merde"  fullword wide ascii nocase
    $  =  "merdeuse"  fullword wide ascii nocase
    $  =  "merdeux"  fullword wide ascii nocase
    $  =  "meuf"  fullword wide ascii nocase
    $  =  "ménage à trois"  fullword wide ascii nocase
    $  =  "nique ta mère"  fullword wide ascii nocase
    $  =  "nique ta race"  fullword wide ascii nocase
    $  =  "nègre"  fullword wide ascii nocase
    $  =  "palucher"  fullword wide ascii nocase
    $  =  "pipi"  fullword wide ascii nocase
    $  =  "pisser"  fullword wide ascii nocase
    $  =  "pouffiasse"  fullword wide ascii nocase
    $  =  "pousse-crotte"  fullword wide ascii nocase
    $  =  "putain"  fullword wide ascii nocase
    $  =  "pute"  fullword wide ascii nocase
    $  =  "pédale"  fullword wide ascii nocase
    $  =  "pédé"  fullword wide ascii nocase
    $  =  "péter"  fullword wide ascii nocase
    $  =  "ramoner"  fullword wide ascii nocase
    $  =  "sac à merde"  fullword wide ascii nocase
    $  =  "salaud"  fullword wide ascii nocase
    $  =  "salope"  fullword wide ascii nocase
    $  =  "suce"  fullword wide ascii nocase
    $  =  "tapette"  fullword wide ascii nocase
    $  =  "teuf"  fullword wide ascii nocase
    $  =  "tringler"  fullword wide ascii nocase
    $  =  "trique"  fullword wide ascii nocase
    $  =  "trou du cul"  fullword wide ascii nocase
    $  =  "turlute"  fullword wide ascii nocase
    $  =  "veuve"  fullword wide ascii nocase
    $  =  "zigounette"  fullword wide ascii nocase
    $  =  "zizi"  fullword wide ascii nocase
    $  =  "étron"  fullword wide ascii nocase
  condition:
    1 of them
}
