rule content_hi_language_nsfw {
  strings:
    $  =  "aand"  fullword wide ascii nocase
    $  =  "aandu"  fullword wide ascii nocase
    $  =  "balatkar"  fullword wide ascii nocase
    $  =  "beti chod"  fullword wide ascii nocase
    $  =  "bhadva"  fullword wide ascii nocase
    $  =  "bhadve"  fullword wide ascii nocase
    $  =  "bhandve"  fullword wide ascii nocase
    $  =  "bhootni ke"  fullword wide ascii nocase
    $  =  "bhosad"  fullword wide ascii nocase
    $  =  "bhosadi ke"  fullword wide ascii nocase
    $  =  "boobe"  fullword wide ascii nocase
    $  =  "chakke"  fullword wide ascii nocase
    $  =  "chinaal"  fullword wide ascii nocase
    $  =  "chinki"  fullword wide ascii nocase
    $  =  "chod"  fullword wide ascii nocase
    $  =  "chodu"  fullword wide ascii nocase
    $  =  "chodu bhagat"  fullword wide ascii nocase
    $  =  "chooche"  fullword wide ascii nocase
    $  =  "choochi"  fullword wide ascii nocase
    $  =  "choot"  fullword wide ascii nocase
    $  =  "choot ke baal"  fullword wide ascii nocase
    $  =  "chootia"  fullword wide ascii nocase
    $  =  "chootiya"  fullword wide ascii nocase
    $  =  "chuche"  fullword wide ascii nocase
    $  =  "chuchi"  fullword wide ascii nocase
    $  =  "chudai khanaa"  fullword wide ascii nocase
    $  =  "chudan chudai"  fullword wide ascii nocase
    $  =  "chut"  fullword wide ascii nocase
    $  =  "chut ke baal"  fullword wide ascii nocase
    $  =  "chut ke dhakkan"  fullword wide ascii nocase
    $  =  "chut maarli"  fullword wide ascii nocase
    $  =  "chutad"  fullword wide ascii nocase
    $  =  "chutadd"  fullword wide ascii nocase
    $  =  "chutan"  fullword wide ascii nocase
    $  =  "chutia"  fullword wide ascii nocase
    $  =  "chutiya"  fullword wide ascii nocase
    $  =  "gaand"  fullword wide ascii nocase
    $  =  "gaandfat"  fullword wide ascii nocase
    $  =  "gaandmasti"  fullword wide ascii nocase
    $  =  "gaandufad"  fullword wide ascii nocase
    $  =  "gandu"  fullword wide ascii nocase
    $  =  "gashti"  fullword wide ascii nocase
    $  =  "gasti"  fullword wide ascii nocase
    $  =  "ghassa"  fullword wide ascii nocase
    $  =  "ghasti"  fullword wide ascii nocase
    $  =  "harami"  fullword wide ascii nocase
    $  =  "haramzade"  fullword wide ascii nocase
    $  =  "hawas"  fullword wide ascii nocase
    $  =  "hawas ke pujari"  fullword wide ascii nocase
    $  =  "hijda"  fullword wide ascii nocase
    $  =  "hijra"  fullword wide ascii nocase
    $  =  "jhant"  fullword wide ascii nocase
    $  =  "jhant chaatu"  fullword wide ascii nocase
    $  =  "jhant ke baal"  fullword wide ascii nocase
    $  =  "jhantu"  fullword wide ascii nocase
    $  =  "kamine"  fullword wide ascii nocase
    $  =  "kaminey"  fullword wide ascii nocase
    $  =  "kanjar"  fullword wide ascii nocase
    $  =  "kutta"  fullword wide ascii nocase
    $  =  "kutta kamina"  fullword wide ascii nocase
    $  =  "kutte ki aulad"  fullword wide ascii nocase
    $  =  "kutte ki jat"  fullword wide ascii nocase
    $  =  "kuttiya"  fullword wide ascii nocase
    $  =  "loda"  fullword wide ascii nocase
    $  =  "lodu"  fullword wide ascii nocase
    $  =  "lund"  fullword wide ascii nocase
    $  =  "lund choos"  fullword wide ascii nocase
    $  =  "lund khajoor"  fullword wide ascii nocase
    $  =  "lundtopi"  fullword wide ascii nocase
    $  =  "lundure"  fullword wide ascii nocase
    $  =  "maa ki chut"  fullword wide ascii nocase
    $  =  "maal"  fullword wide ascii nocase
    $  =  "madar chod"  fullword wide ascii nocase
    $  =  "mooh mein le"  fullword wide ascii nocase
    $  =  "mutth"  fullword wide ascii nocase
    $  =  "najayaz"  fullword wide ascii nocase
    $  =  "najayaz aulaad"  fullword wide ascii nocase
    $  =  "najayaz paidaish"  fullword wide ascii nocase
    $  =  "paki"  fullword wide ascii nocase
    $  =  "pataka"  fullword wide ascii nocase
    $  =  "patakha"  fullword wide ascii nocase
    $  =  "raand"  fullword wide ascii nocase
    $  =  "randi"  fullword wide ascii nocase
    $  =  "saala"  fullword wide ascii nocase
    $  =  "saala kutta"  fullword wide ascii nocase
    $  =  "saali kutti"  fullword wide ascii nocase
    $  =  "saali randi"  fullword wide ascii nocase
    $  =  "suar"  fullword wide ascii nocase
    $  =  "suar ki aulad"  fullword wide ascii nocase
    $  =  "tatte"  fullword wide ascii nocase
    $  =  "tatti"  fullword wide ascii nocase
    $  =  "teri maa ka bhosada"  fullword wide ascii nocase
    $  =  "teri maa ka boba chusu"  fullword wide ascii nocase
    $  =  "teri maa ki chut"  fullword wide ascii nocase
    $  =  "tharak"  fullword wide ascii nocase
    $  =  "tharki"  fullword wide ascii nocase
  condition:
    1 of them
}
