rule content_it_language_nsfw {
  strings:
      $  =  "allupato"  fullword wide ascii nocase
      $  =  "ammucchiata"  fullword wide ascii nocase
      $  =  "anale"  fullword wide ascii nocase
      $  =  "arrapato"  fullword wide ascii nocase
      $  =  "arrusa"  fullword wide ascii nocase
      $  =  "arruso"  fullword wide ascii nocase
      $  =  "assatanato"  fullword wide ascii nocase
      $  =  "bagascia"  fullword wide ascii nocase
      $  =  "bagassa"  fullword wide ascii nocase
      $  =  "bagnarsi"  fullword wide ascii nocase
      $  =  "baldracca"  fullword wide ascii nocase
      $  =  "balle"  fullword wide ascii nocase
      $  =  "battere"  fullword wide ascii nocase
      $  =  "battona"  fullword wide ascii nocase
      $  =  "belino"  fullword wide ascii nocase
      $  =  "biga"  fullword wide ascii nocase
      $  =  "bocchinara"  fullword wide ascii nocase
      $  =  "bocchino"  fullword wide ascii nocase
      $  =  "bofilo"  fullword wide ascii nocase
      $  =  "boiata"  fullword wide ascii nocase
      $  =  "bordello"  fullword wide ascii nocase
      $  =  "brinca"  fullword wide ascii nocase
      $  =  "bucaiolo"  fullword wide ascii nocase
      $  =  "budiùlo"  fullword wide ascii nocase
      $  =  "buona donna"  fullword wide ascii nocase
      $  =  "busone"  fullword wide ascii nocase
      $  =  "cacca"  fullword wide ascii nocase
      $  =  "caccati in mano e prenditi a schiaffi"  fullword wide ascii nocase
      $  =  "caciocappella"  fullword wide ascii nocase
      $  =  "cadavere"  fullword wide ascii nocase
      $  =  "cagare"  fullword wide ascii nocase
      $  =  "cagata"  fullword wide ascii nocase
      $  =  "cagna"  fullword wide ascii nocase
      $  =  "cammello"  fullword wide ascii nocase
      $  =  "cappella"  fullword wide ascii nocase
      $  =  "carciofo"  fullword wide ascii nocase
      $  =  "carità"  fullword wide ascii nocase
      $  =  "casci"  fullword wide ascii nocase
      $  =  "cazzata"  fullword wide ascii nocase
      $  =  "cazzimma"  fullword wide ascii nocase
      $  =  "cazzo"  fullword wide ascii nocase
      $  =  "checca"  fullword wide ascii nocase
      $  =  "chiappa"  fullword wide ascii nocase
      $  =  "chiavare"  fullword wide ascii nocase
      $  =  "chiavata"  fullword wide ascii nocase
      $  =  "ciospo"  fullword wide ascii nocase
      $  =  "ciucciami il cazzo"  fullword wide ascii nocase
      $  =  "coglione"  fullword wide ascii nocase
      $  =  "coglioni"  fullword wide ascii nocase
      $  =  "cornuto"  fullword wide ascii nocase
      $  =  "cozza"  fullword wide ascii nocase
      $  =  "culattina"  fullword wide ascii nocase
      $  =  "culattone"  fullword wide ascii nocase
      $  =  "culo"  fullword wide ascii nocase
      $  =  "di merda"  fullword wide ascii nocase
      $  =  "ditalino"  fullword wide ascii nocase
      $  =  "duro"  fullword wide ascii nocase
      $  =  "fare unaŠ"  fullword wide ascii nocase
      $  =  "fava"  fullword wide ascii nocase
      $  =  "femminuccia"  fullword wide ascii nocase
      $  =  "fica"  fullword wide ascii nocase
      $  =  "figa"  fullword wide ascii nocase
      $  =  "figlio di buona donna"  fullword wide ascii nocase
      $  =  "figlio di puttana"  fullword wide ascii nocase
      $  =  "figone"  fullword wide ascii nocase
      $  =  "finocchio"  fullword wide ascii nocase
      $  =  "fottere"  fullword wide ascii nocase
      $  =  "fottersi"  fullword wide ascii nocase
      $  =  "fracicone"  fullword wide ascii nocase
      $  =  "fregna"  fullword wide ascii nocase
      $  =  "frocio"  fullword wide ascii nocase
      $  =  "froscio"  fullword wide ascii nocase
      $  =  "fuori come un balcone"  fullword wide ascii nocase
      $  =  "goldone"  fullword wide ascii nocase
      $  =  "grilletto"  fullword wide ascii nocase
      $  =  "guanto"  fullword wide ascii nocase
      $  =  "guardone"  fullword wide ascii nocase
      $  =  "incazzarsi"  fullword wide ascii nocase
      $  =  "incoglionirsi"  fullword wide ascii nocase
      $  =  "ingoio"  fullword wide ascii nocase
      $  =  "l'arte bolognese"  fullword wide ascii nocase
      $  =  "leccaculo"  fullword wide ascii nocase
      $  =  "lecchino"  fullword wide ascii nocase
      $  =  "lofare"  fullword wide ascii nocase
      $  =  "loffa"  fullword wide ascii nocase
      $  =  "loffare"  fullword wide ascii nocase
      $  =  "lumaca"  fullword wide ascii nocase
      $  =  "manico"  fullword wide ascii nocase
      $  =  "mannaggia"  fullword wide ascii nocase
      $  =  "merda"  fullword wide ascii nocase
      $  =  "merdata"  fullword wide ascii nocase
      $  =  "merdoso"  fullword wide ascii nocase
      $  =  "mignotta"  fullword wide ascii nocase
      $  =  "minchia"  fullword wide ascii nocase
      $  =  "minchione"  fullword wide ascii nocase
      $  =  "mona"  fullword wide ascii nocase
      $  =  "monta"  fullword wide ascii nocase
      $  =  "montare"  fullword wide ascii nocase
      $  =  "mussa"  fullword wide ascii nocase
      $  =  "nave scuola"  fullword wide ascii nocase
      $  =  "nerchia"  fullword wide ascii nocase
      $  =  "nudo"  fullword wide ascii nocase
      $  =  "padulo"  fullword wide ascii nocase
      $  =  "palle"  fullword wide ascii nocase
      $  =  "palloso"  fullword wide ascii nocase
      $  =  "patacca"  fullword wide ascii nocase
      $  =  "patonza"  fullword wide ascii nocase
      $  =  "pecorina"  fullword wide ascii nocase
      $  =  "pesce"  fullword wide ascii nocase
      $  =  "picio"  fullword wide ascii nocase
      $  =  "pincare"  fullword wide ascii nocase
      $  =  "pipa"  fullword wide ascii nocase
      $  =  "pippone"  fullword wide ascii nocase
      $  =  "pipì"  fullword wide ascii nocase
      $  =  "pirla"  fullword wide ascii nocase
      $  =  "pisciare"  fullword wide ascii nocase
      $  =  "piscio"  fullword wide ascii nocase
      $  =  "pisello"  fullword wide ascii nocase
      $  =  "pistola"  fullword wide ascii nocase
      $  =  "pistolotto"  fullword wide ascii nocase
      $  =  "pomiciare"  fullword wide ascii nocase
      $  =  "pompa"  fullword wide ascii nocase
      $  =  "pompino"  fullword wide ascii nocase
      $  =  "porca"  fullword wide ascii nocase
      $  =  "porca madonna"  fullword wide ascii nocase
      $  =  "porca miseria"  fullword wide ascii nocase
      $  =  "porca puttana"  fullword wide ascii nocase
      $  =  "porco due"  fullword wide ascii nocase
      $  =  "porco zio"  fullword wide ascii nocase
      $  =  "potta"  fullword wide ascii nocase
      $  =  "puppami"  fullword wide ascii nocase
      $  =  "puttana"  fullword wide ascii nocase
      $  =  "quaglia"  fullword wide ascii nocase
      $  =  "recchione"  fullword wide ascii nocase
      $  =  "regina"  fullword wide ascii nocase
      $  =  "rincoglionire"  fullword wide ascii nocase
      $  =  "rizzarsi"  fullword wide ascii nocase
      $  =  "rompiballe"  fullword wide ascii nocase
      $  =  "ruffiano"  fullword wide ascii nocase
      $  =  "sbattere"  fullword wide ascii nocase
      $  =  "sbattersi"  fullword wide ascii nocase
      $  =  "sborra"  fullword wide ascii nocase
      $  =  "sborrata"  fullword wide ascii nocase
      $  =  "sborrone"  fullword wide ascii nocase
      $  =  "sbrodolata"  fullword wide ascii nocase
      $  =  "scopare"  fullword wide ascii nocase
      $  =  "scopata"  fullword wide ascii nocase
      $  =  "scorreggiare"  fullword wide ascii nocase
      $  =  "sega"  fullword wide ascii nocase
      $  =  "slinguare"  fullword wide ascii nocase
      $  =  "slinguata"  fullword wide ascii nocase
      $  =  "smandrappata"  fullword wide ascii nocase
      $  =  "soccia"  fullword wide ascii nocase
      $  =  "socmel"  fullword wide ascii nocase
      $  =  "sorca"  fullword wide ascii nocase
      $  =  "spagnola"  fullword wide ascii nocase
      $  =  "spompinare"  fullword wide ascii nocase
      $  =  "sticchio"  fullword wide ascii nocase
      $  =  "stronza"  fullword wide ascii nocase
      $  =  "stronzata"  fullword wide ascii nocase
      $  =  "stronzo"  fullword wide ascii nocase
      $  =  "succhiami"  fullword wide ascii nocase
      $  =  "sveltina"  fullword wide ascii nocase
      $  =  "sverginare"  fullword wide ascii nocase
      $  =  "tarzanello"  fullword wide ascii nocase
      $  =  "terrone"  fullword wide ascii nocase
      $  =  "testa di cazzo"  fullword wide ascii nocase
      $  =  "tette"  fullword wide ascii nocase
      $  =  "tirare"  fullword wide ascii nocase
      $  =  "topa"  fullword wide ascii nocase
      $  =  "troia"  fullword wide ascii nocase
      $  =  "trombare"  fullword wide ascii nocase
      $  =  "uccello"  fullword wide ascii nocase
      $  =  "vacca"  fullword wide ascii nocase
      $  =  "vaffanculo"  fullword wide ascii nocase
      $  =  "vangare"  fullword wide ascii nocase
      $  =  "venire"  fullword wide ascii nocase
      $  =  "zinne"  fullword wide ascii nocase
      $  =  "zio cantante"  fullword wide ascii nocase
      $  =  "zoccola"  fullword wide ascii nocase
  condition:
    1 of them
}
