/*
* Bundle rule that include all underlying languages
*/
include "cs-language-nsfw.yara"
include "da-language-nsfw.yara"
include "de-language-nsfw.yara"
include "en-language-nsfw.yara"
include "eo-language-nsfw.yara"
include "es-language-nsfw.yara"
include "fi-language-nsfw.yara"
include "fr-language-nsfw.yara"
include "hi-language-nsfw.yara"
include "hu-language-nsfw.yara"
include "it-language-nsfw.yara"
include "ja-language-nsfw.yara"
include "ko-language-nsfw.yara"
include "nl-language-nsfw.yara"
include "no-language-nsfw.yara"
include "pl-language-nsfw.yara"
include "pt-language-nsfw.yara"
include "ru-language-nsfw.yara"
include "sv-language-nsfw.yara"
include "th-language-nsfw.yara"
include "tlh-language-nsfw.yara"
include "tr-language-nsfw.yara"
include "zh-language-nsfw.yara"
