rule content_nl_language_nsfw {
  strings:
      $  =  "aardappels afgieteng"  fullword wide ascii nocase
      $  =  "achter het raam zitten"  fullword wide ascii nocase
      $  =  "afberen"  fullword wide ascii nocase
      $  =  "aflebberen"  fullword wide ascii nocase
      $  =  "afrossen"  fullword wide ascii nocase
      $  =  "afrukken"  fullword wide ascii nocase
      $  =  "aftrekken"  fullword wide ascii nocase
      $  =  "afwerkplaats"  fullword wide ascii nocase
      $  =  "afzeiken"  fullword wide ascii nocase
      $  =  "afzuigen"  fullword wide ascii nocase
      $  =  "anderhalve man en een paardekop"  fullword wide ascii nocase
      $  =  "anita"  fullword wide ascii nocase
      $  =  "asbak"  fullword wide ascii nocase
      $  =  "aso"  fullword wide ascii nocase
      $  =  "bagger schijten"  fullword wide ascii nocase
      $  =  "balen"  fullword wide ascii nocase
      $  =  "bedonderen"  fullword wide ascii nocase
      $  =  "befborstelg"  fullword wide ascii nocase
      $  =  "beffen"  fullword wide ascii nocase
      $  =  "bekken"  fullword wide ascii nocase
      $  =  "belazeren"  fullword wide ascii nocase
      $  =  "besodemieterd zijn"  fullword wide ascii nocase
      $  =  "besodemieteren"  fullword wide ascii nocase
      $  =  "beurt"  fullword wide ascii nocase
      $  =  "boemelen"  fullword wide ascii nocase
      $  =  "boerelul"  fullword wide ascii nocase
      $  =  "boerenpummelg"  fullword wide ascii nocase
      $  =  "bokkelul"  fullword wide ascii nocase
      $  =  "botergeil"  fullword wide ascii nocase
      $  =  "broekhoesten"  fullword wide ascii nocase
      $  =  "brugpieperg"  fullword wide ascii nocase
      $  =  "buffelen"  fullword wide ascii nocase
      $  =  "buiten de pot piesen"  fullword wide ascii nocase
      $  =  "da's kloten van de bok"  fullword wide ascii nocase
      $  =  "de ballen"  fullword wide ascii nocase
      $  =  "de hoer spelen"  fullword wide ascii nocase
      $  =  "de hond uitlaten"  fullword wide ascii nocase
      $  =  "de koffer induiken"  fullword wide ascii nocase
      $  =  "de pijp aan maarten geven"  fullword wide ascii nocase
      $  =  "de pijp uitgaan"  fullword wide ascii nocase
      $  =  "delg"  fullword wide ascii nocase
      $  =  "dombo"  fullword wide ascii nocase
      $  =  "draaikontg"  fullword wide ascii nocase
      $  =  "driehoog achter wonen"  fullword wide ascii nocase
      $  =  "drolg"  fullword wide ascii nocase
      $  =  "drooggeiler"  fullword wide ascii nocase
      $  =  "droogkloot"  fullword wide ascii nocase
      $  =  "een beurt geven"  fullword wide ascii nocase
      $  =  "een nummertje maken"  fullword wide ascii nocase
      $  =  "een wip maken"  fullword wide ascii nocase
      $  =  "eikel"  fullword wide ascii nocase
      $  =  "engerd"  fullword wide ascii nocase
      $  =  "flamoes"  fullword wide ascii nocase
      $  =  "flikken"  fullword wide ascii nocase
      $  =  "flikker"  fullword wide ascii nocase
      $  =  "gadverdamme"  fullword wide ascii nocase
      $  =  "galbak"  fullword wide ascii nocase
      $  =  "gat"  fullword wide ascii nocase
      $  =  "gedoogzone"  fullword wide ascii nocase
      $  =  "geilneef"  fullword wide ascii nocase
      $  =  "gesodemieter"  fullword wide ascii nocase
      $  =  "godverdomme"  fullword wide ascii nocase
      $  =  "graftak"  fullword wide ascii nocase
      $  =  "gras maaien"  fullword wide ascii nocase
      $  =  "gratenkutg"  fullword wide ascii nocase
      $  =  "greppeldel"  fullword wide ascii nocase
      $  =  "griet"  fullword wide ascii nocase
      $  =  "hoempert"  fullword wide ascii nocase
      $  =  "hoer"  fullword wide ascii nocase
      $  =  "hoerenbuurt"  fullword wide ascii nocase
      $  =  "hoerenloper"  fullword wide ascii nocase
      $  =  "hoerig"  fullword wide ascii nocase
      $  =  "hol"  fullword wide ascii nocase
      $  =  "hufter"  fullword wide ascii nocase
      $  =  "huisdealer"  fullword wide ascii nocase
      $  =  "johny"  fullword wide ascii nocase
      $  =  "kanen"  fullword wide ascii nocase
      $  =  "kettingzeugg"  fullword wide ascii nocase
      $  =  "klaarkomen"  fullword wide ascii nocase
      $  =  "klerebeer"  fullword wide ascii nocase
      $  =  "klojo"  fullword wide ascii nocase
      $  =  "klooien"  fullword wide ascii nocase
      $  =  "klootjesvolk"  fullword wide ascii nocase
      $  =  "klootoog"  fullword wide ascii nocase
      $  =  "klootzak"  fullword wide ascii nocase
      $  =  "kloten"  fullword wide ascii nocase
      $  =  "knor"  fullword wide ascii nocase
      $  =  "kontg"  fullword wide ascii nocase
      $  =  "kontneuken"  fullword wide ascii nocase
      $  =  "krentekakker"  fullword wide ascii nocase
      $  =  "kut"  fullword wide ascii nocase
      $  =  "kuttelikkertje"  fullword wide ascii nocase
      $  =  "kwakkieg"  fullword wide ascii nocase
      $  =  "liefdesgrot"  fullword wide ascii nocase
      $  =  "lul"  fullword wide ascii nocase
      $  =  "lul-de-behanger"  fullword wide ascii nocase
      $  =  "lulhannes"  fullword wide ascii nocase
      $  =  "lummel"  fullword wide ascii nocase
      $  =  "mafketel"  fullword wide ascii nocase
      $  =  "matennaaierg"  fullword wide ascii nocase
      $  =  "matje"  fullword wide ascii nocase
      $  =  "mof"  fullword wide ascii nocase
      $  =  "mutsg"  fullword wide ascii nocase
      $  =  "naaien"  fullword wide ascii nocase
      $  =  "naakt"  fullword wide ascii nocase
      $  =  "neuken"  fullword wide ascii nocase
      $  =  "neukstier"  fullword wide ascii nocase
      $  =  "nicht"  fullword wide ascii nocase
      $  =  "oetlul"  fullword wide ascii nocase
      $  =  "op z'n hondjes"  fullword wide ascii nocase
      $  =  "op z'n sodemieter geven"  fullword wide ascii nocase
      $  =  "opgeilen"  fullword wide ascii nocase
      $  =  "opkankeren"  fullword wide ascii nocase
      $  =  "oprotten"  fullword wide ascii nocase
      $  =  "opsodemieteren"  fullword wide ascii nocase
      $  =  "opzouten"  fullword wide ascii nocase
      $  =  "ouwe rukker"  fullword wide ascii nocase
      $  =  "ouwehoer"  fullword wide ascii nocase
      $  =  "ouwehoeren"  fullword wide ascii nocase
      $  =  "paal"  fullword wide ascii nocase
      $  =  "paardelul"  fullword wide ascii nocase
      $  =  "palen"  fullword wide ascii nocase
      $  =  "penozeg"  fullword wide ascii nocase
      $  =  "piesen"  fullword wide ascii nocase
      $  =  "pijpbekkieg"  fullword wide ascii nocase
      $  =  "pijpen"  fullword wide ascii nocase
      $  =  "pik"  fullword wide ascii nocase
      $  =  "pleurislaaier"  fullword wide ascii nocase
      $  =  "poep"  fullword wide ascii nocase
      $  =  "poepen"  fullword wide ascii nocase
      $  =  "poot"  fullword wide ascii nocase
      $  =  "portiekslet"  fullword wide ascii nocase
      $  =  "pot"  fullword wide ascii nocase
      $  =  "potverdorie"  fullword wide ascii nocase
      $  =  "publiciteitsgeil"  fullword wide ascii nocase
      $  =  "raaskallen"  fullword wide ascii nocase
      $  =  "reet"  fullword wide ascii nocase
      $  =  "reet trappen, voor zijn"  fullword wide ascii nocase
      $  =  "reetridder"  fullword wide ascii nocase
      $  =  "remsporeng"  fullword wide ascii nocase
      $  =  "reutelen"  fullword wide ascii nocase
      $  =  "rothoer"  fullword wide ascii nocase
      $  =  "rotzak"  fullword wide ascii nocase
      $  =  "rukhond"  fullword wide ascii nocase
      $  =  "rukken"  fullword wide ascii nocase
      $  =  "schatje"  fullword wide ascii nocase
      $  =  "schijt"  fullword wide ascii nocase
      $  =  "schijten"  fullword wide ascii nocase
      $  =  "schoft"  fullword wide ascii nocase
      $  =  "schuinsmarcheerder"  fullword wide ascii nocase
      $  =  "shit"  fullword wide ascii nocase
      $  =  "slempen"  fullword wide ascii nocase
      $  =  "sletg"  fullword wide ascii nocase
      $  =  "sletterig"  fullword wide ascii nocase
      $  =  "slik mijn zaad"  fullword wide ascii nocase
      $  =  "snolg"  fullword wide ascii nocase
      $  =  "spuiten"  fullword wide ascii nocase
      $  =  "standje"  fullword wide ascii nocase
      $  =  "standje-69g"  fullword wide ascii nocase
      $  =  "stoephoer"  fullword wide ascii nocase
      $  =  "stootje"  fullword wide ascii nocase
      $  =  "strontg"  fullword wide ascii nocase
      $  =  "sufferdg"  fullword wide ascii nocase
      $  =  "tapijtnek"  fullword wide ascii nocase
      $  =  "teefg"  fullword wide ascii nocase
      $  =  "temeier"  fullword wide ascii nocase
      $  =  "teringlijer"  fullword wide ascii nocase
      $  =  "toeter"  fullword wide ascii nocase
      $  =  "tongzoeng"  fullword wide ascii nocase
      $  =  "triootjeg"  fullword wide ascii nocase
      $  =  "trottoir prostituée"  fullword wide ascii nocase
      $  =  "trottoirteef"  fullword wide ascii nocase
      $  =  "vergallen"  fullword wide ascii nocase
      $  =  "verkloten"  fullword wide ascii nocase
      $  =  "verneuken"  fullword wide ascii nocase
      $  =  "viespeuk"  fullword wide ascii nocase
      $  =  "vingeren"  fullword wide ascii nocase
      $  =  "vleesroos"  fullword wide ascii nocase
      $  =  "voor jan lul"  fullword wide ascii nocase
      $  =  "voor jan-met-de-korte-achternaam"  fullword wide ascii nocase
      $  =  "watje"  fullword wide ascii nocase
      $  =  "welzijnsmafia"  fullword wide ascii nocase
      $  =  "wijf"  fullword wide ascii nocase
      $  =  "wippen"  fullword wide ascii nocase
      $  =  "wuftje"  fullword wide ascii nocase
      $  =  "zaadje"  fullword wide ascii nocase
      $  =  "zakkenwasser"  fullword wide ascii nocase
      $  =  "zeiken"  fullword wide ascii nocase
      $  =  "zeiker"  fullword wide ascii nocase
      $  =  "zuigen"  fullword wide ascii nocase
      $  =  "zuiplap"  fullword wide ascii nocase
  condition:
    1 of them
}
