rule content_pt_language_nsfw {
  strings:
      $  =  "aborto"  fullword wide ascii nocase
      $  =  "amador"  fullword wide ascii nocase
      $  =  "aranha"  fullword wide ascii nocase
      $  =  "ariano"  fullword wide ascii nocase
      $  =  "balalao"  fullword wide ascii nocase
      $  =  "bastardo"  fullword wide ascii nocase
      $  =  "bicha"  fullword wide ascii nocase
      $  =  "biscate"  fullword wide ascii nocase
      $  =  "bissexual"  fullword wide ascii nocase
      $  =  "boceta"  fullword wide ascii nocase
      $  =  "boob"  fullword wide ascii nocase
      $  =  "bosta"  fullword wide ascii nocase
      $  =  "braulio de borracha"  fullword wide ascii nocase
      $  =  "bumbum"  fullword wide ascii nocase
      $  =  "burro"  fullword wide ascii nocase
      $  =  "cabrao"  fullword wide ascii nocase
      $  =  "cacete"  fullword wide ascii nocase
      $  =  "cagar"  fullword wide ascii nocase
      $  =  "camisinha"  fullword wide ascii nocase
      $  =  "caralho"  fullword wide ascii nocase
      $  =  "cerveja"  fullword wide ascii nocase
      $  =  "chochota"  fullword wide ascii nocase
      $  =  "chupar"  fullword wide ascii nocase
      $  =  "clitoris"  fullword wide ascii nocase
      $  =  "cocaína"  fullword wide ascii nocase
      $  =  "colhoes"  fullword wide ascii nocase
      $  =  "cona"  fullword wide ascii nocase
      $  =  "consolo"  fullword wide ascii nocase
      $  =  "corno"  fullword wide ascii nocase
      $  =  "cu"  fullword wide ascii nocase
      $  =  "dar o rabo"  fullword wide ascii nocase
      $  =  "dum raio"  fullword wide ascii nocase
      $  =  "esporra"  fullword wide ascii nocase
      $  =  "fecal"  fullword wide ascii nocase
      $  =  "filho da puta"  fullword wide ascii nocase
      $  =  "foda"  fullword wide ascii nocase
      $  =  "foda-se"  fullword wide ascii nocase
      $  =  "foder"  fullword wide ascii nocase
      $  =  "frango assado"  fullword wide ascii nocase
      $  =  "gozar"  fullword wide ascii nocase
      $  =  "grelho"  fullword wide ascii nocase
      $  =  "heroína"  fullword wide ascii nocase
      $  =  "homoerótico"  fullword wide ascii nocase
      $  =  "inferno"  fullword wide ascii nocase
      $  =  "lolita"  fullword wide ascii nocase
      $  =  "lésbica"  fullword wide ascii nocase
      $  =  "mama"  fullword wide ascii nocase
      $  =  "merda"  fullword wide ascii nocase
      $  =  "paneleiro"  fullword wide ascii nocase
      $  =  "passar um cheque"  fullword wide ascii nocase
      $  =  "pau"  fullword wide ascii nocase
      $  =  "peidar"  fullword wide ascii nocase
      $  =  "pinto"  fullword wide ascii nocase
      $  =  "porra"  fullword wide ascii nocase
      $  =  "puta"  fullword wide ascii nocase
      $  =  "puta que pariu"  fullword wide ascii nocase
      $  =  "puta que te pariu"  fullword wide ascii nocase
      $  =  "pênis"  fullword wide ascii nocase
      $  =  "queca"  fullword wide ascii nocase
      $  =  "sacanagem"  fullword wide ascii nocase
      $  =  "saco"  fullword wide ascii nocase
      $  =  "torneira"  fullword wide ascii nocase
      $  =  "transar"  fullword wide ascii nocase
      $  =  "vai tomar no cu"  fullword wide ascii nocase
      $  =  "vai-te foder"  fullword wide ascii nocase
      $  =  "veado"  fullword wide ascii nocase
      $  =  "vibrador"  fullword wide ascii nocase
      $  =  "xana"  fullword wide ascii nocase
      $  =  "xochota"  fullword wide ascii nocase
      $  =  "ânus"  fullword wide ascii nocase
  condition:
    1 of them
}
