rule content_tr_language_nsfw {
  strings:
      $  =  "amcık"  fullword wide ascii nocase
      $  =  "amcıklar"  fullword wide ascii nocase
      $  =  "amcıklara"  fullword wide ascii nocase
      $  =  "amcıklarda"  fullword wide ascii nocase
      $  =  "amcıklardan"  fullword wide ascii nocase
      $  =  "amcıkları"  fullword wide ascii nocase
      $  =  "amcıkların"  fullword wide ascii nocase
      $  =  "amcıkta"  fullword wide ascii nocase
      $  =  "amcıktan"  fullword wide ascii nocase
      $  =  "amcığa"  fullword wide ascii nocase
      $  =  "amcığı"  fullword wide ascii nocase
      $  =  "amcığın"  fullword wide ascii nocase
      $  =  "amlar"  fullword wide ascii nocase
      $  =  "amı"  fullword wide ascii nocase
      $  =  "göt"  fullword wide ascii nocase
      $  =  "göte"  fullword wide ascii nocase
      $  =  "götler"  fullword wide ascii nocase
      $  =  "götlerde"  fullword wide ascii nocase
      $  =  "götlerden"  fullword wide ascii nocase
      $  =  "götlere"  fullword wide ascii nocase
      $  =  "götleri"  fullword wide ascii nocase
      $  =  "götlerin"  fullword wide ascii nocase
      $  =  "götte"  fullword wide ascii nocase
      $  =  "götten"  fullword wide ascii nocase
      $  =  "götveren"  fullword wide ascii nocase
      $  =  "götverende"  fullword wide ascii nocase
      $  =  "götverenden"  fullword wide ascii nocase
      $  =  "götverene"  fullword wide ascii nocase
      $  =  "götvereni"  fullword wide ascii nocase
      $  =  "götverenin"  fullword wide ascii nocase
      $  =  "götverenler"  fullword wide ascii nocase
      $  =  "götverenlerde"  fullword wide ascii nocase
      $  =  "götverenlerden"  fullword wide ascii nocase
      $  =  "götverenlere"  fullword wide ascii nocase
      $  =  "götverenleri"  fullword wide ascii nocase
      $  =  "götverenlerin"  fullword wide ascii nocase
      $  =  "götü"  fullword wide ascii nocase
      $  =  "götün"  fullword wide ascii nocase
      $  =  "kaltak"  fullword wide ascii nocase
      $  =  "kaltaklar"  fullword wide ascii nocase
      $  =  "kaltaklara"  fullword wide ascii nocase
      $  =  "kaltaklarda"  fullword wide ascii nocase
      $  =  "kaltaklardan"  fullword wide ascii nocase
      $  =  "kaltakları"  fullword wide ascii nocase
      $  =  "kaltakların"  fullword wide ascii nocase
      $  =  "kaltakta"  fullword wide ascii nocase
      $  =  "kaltaktan"  fullword wide ascii nocase
      $  =  "kaltağa"  fullword wide ascii nocase
      $  =  "kaltağı"  fullword wide ascii nocase
      $  =  "kaltağın"  fullword wide ascii nocase
      $  =  "orospu"  fullword wide ascii nocase
      $  =  "orospuda"  fullword wide ascii nocase
      $  =  "orospudan"  fullword wide ascii nocase
      $  =  "orospular"  fullword wide ascii nocase
      $  =  "orospulara"  fullword wide ascii nocase
      $  =  "orospularda"  fullword wide ascii nocase
      $  =  "orospulardan"  fullword wide ascii nocase
      $  =  "orospuları"  fullword wide ascii nocase
      $  =  "orospuların"  fullword wide ascii nocase
      $  =  "orospunun"  fullword wide ascii nocase
      $  =  "orospuya"  fullword wide ascii nocase
      $  =  "orospuyu"  fullword wide ascii nocase
      $  =  "otuz birci"  fullword wide ascii nocase
      $  =  "otuz bircide"  fullword wide ascii nocase
      $  =  "otuz birciden"  fullword wide ascii nocase
      $  =  "otuz birciler"  fullword wide ascii nocase
      $  =  "otuz bircilerde"  fullword wide ascii nocase
      $  =  "otuz bircilerden"  fullword wide ascii nocase
      $  =  "otuz bircilere"  fullword wide ascii nocase
      $  =  "otuz bircileri"  fullword wide ascii nocase
      $  =  "otuz bircilerin"  fullword wide ascii nocase
      $  =  "otuz bircinin"  fullword wide ascii nocase
      $  =  "otuz birciye"  fullword wide ascii nocase
      $  =  "otuz birciyi"  fullword wide ascii nocase
      $  =  "saksocu"  fullword wide ascii nocase
      $  =  "saksocuda"  fullword wide ascii nocase
      $  =  "saksocudan"  fullword wide ascii nocase
      $  =  "saksocular"  fullword wide ascii nocase
      $  =  "saksoculara"  fullword wide ascii nocase
      $  =  "saksocularda"  fullword wide ascii nocase
      $  =  "saksoculardan"  fullword wide ascii nocase
      $  =  "saksocuları"  fullword wide ascii nocase
      $  =  "saksocuların"  fullword wide ascii nocase
      $  =  "saksocunun"  fullword wide ascii nocase
      $  =  "saksocuya"  fullword wide ascii nocase
      $  =  "saksocuyu"  fullword wide ascii nocase
      $  =  "sik"  fullword wide ascii nocase
      $  =  "sike"  fullword wide ascii nocase
      $  =  "siker sikmez"  fullword wide ascii nocase
      $  =  "siki"  fullword wide ascii nocase
      $  =  "sikilir sikilmez"  fullword wide ascii nocase
      $  =  "sikin"  fullword wide ascii nocase
      $  =  "sikler"  fullword wide ascii nocase
      $  =  "siklerde"  fullword wide ascii nocase
      $  =  "siklerden"  fullword wide ascii nocase
      $  =  "siklere"  fullword wide ascii nocase
      $  =  "sikleri"  fullword wide ascii nocase
      $  =  "siklerin"  fullword wide ascii nocase
      $  =  "sikmek"  fullword wide ascii nocase
      $  =  "sikmemek"  fullword wide ascii nocase
      $  =  "sikte"  fullword wide ascii nocase
      $  =  "sikten"  fullword wide ascii nocase
      $  =  "siktir"  fullword wide ascii nocase
      $  =  "siktirir siktirmez"  fullword wide ascii nocase
      $  =  "sıçmak"  fullword wide ascii nocase
      $  =  "taşak"  fullword wide ascii nocase
      $  =  "taşaklar"  fullword wide ascii nocase
      $  =  "taşaklara"  fullword wide ascii nocase
      $  =  "taşaklarda"  fullword wide ascii nocase
      $  =  "taşaklardan"  fullword wide ascii nocase
      $  =  "taşakları"  fullword wide ascii nocase
      $  =  "taşakların"  fullword wide ascii nocase
      $  =  "taşakta"  fullword wide ascii nocase
      $  =  "taşaktan"  fullword wide ascii nocase
      $  =  "taşağa"  fullword wide ascii nocase
      $  =  "taşağı"  fullword wide ascii nocase
      $  =  "taşağın"  fullword wide ascii nocase
      $  =  "yarak"  fullword wide ascii nocase
      $  =  "yaraklar"  fullword wide ascii nocase
      $  =  "yaraklara"  fullword wide ascii nocase
      $  =  "yaraklarda"  fullword wide ascii nocase
      $  =  "yaraklardan"  fullword wide ascii nocase
      $  =  "yarakları"  fullword wide ascii nocase
      $  =  "yarakların"  fullword wide ascii nocase
      $  =  "yarakta"  fullword wide ascii nocase
      $  =  "yaraktan"  fullword wide ascii nocase
      $  =  "yarağa"  fullword wide ascii nocase
      $  =  "yarağı"  fullword wide ascii nocase
      $  =  "yarağın"  fullword wide ascii nocase
      $  =  "Çingenede"  fullword wide ascii nocase
      $  =  "Çingeneden"  fullword wide ascii nocase
      $  =  "Çingeneler"  fullword wide ascii nocase
      $  =  "Çingenelerde"  fullword wide ascii nocase
      $  =  "Çingenelerden"  fullword wide ascii nocase
      $  =  "Çingenelere"  fullword wide ascii nocase
      $  =  "Çingeneleri"  fullword wide ascii nocase
      $  =  "Çingenelerin"  fullword wide ascii nocase
      $  =  "Çingenenin"  fullword wide ascii nocase
      $  =  "Çingeneye"  fullword wide ascii nocase
      $  =  "Çingeneyi"  fullword wide ascii nocase
      $  =  "çingene"  fullword wide ascii nocase
  condition:
    1 of them
}
