on: pull_request

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    container:
      image: debian:9
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip yara make
      - name: Testing
        run: make test
