on: pull_request

jobs:
  yara-v4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get install -qqy make yara
        env:
          YARA_VERSION: 4.2.3
      - name: Testing
        run: make test
